require "active_support/core_ext/integer/time"

Rails.application.configure do
  # Settings specified here will take precedence over those in config/application.rb.

  # In the development environment your application's code is reloaded any time
  # it changes. This slows down response time but is perfect for development
  # since you don't have to restart the web server when you make code changes.
  config.enable_reloading = true

  # Do not eager load code on boot.
  config.eager_load = false

  # Show full error reports.
  config.consider_all_requests_local = true

  # Enable server timing.
  config.server_timing = true

  # Enable/disable caching. By default caching is disabled.
  # Run rails dev:cache to toggle caching.
  if Rails.root.join("tmp/caching-dev.txt").exist?
    config.cache_store = :memory_store
    config.public_file_server.headers = { "Cache-Control" => "public, max-age=#{2.days.to_i}" }
  else
    config.action_controller.perform_caching = false

    config.cache_store = :null_store
  end

  # Store uploaded files on the local file system (see config/storage.yml for options).
  config.active_storage.service = :local

  # Don't care if the mailer can't send.
  config.action_mailer.raise_delivery_errors = true

  # Disable caching for Action Mailer templates even if Action Controller
  # caching is enabled.
  config.action_mailer.perform_caching = false

  config.action_mailer.default_url_options = { host: "localhost", port: 3000 }

  # Configure Action Mailer to use SMTP (can be overridden with environment variables)
  # config.action_mailer.delivery_method = ENV.fetch('MAILER_DELIVERY_METHOD', 'smtp').to_sym

  # # SMTP settings for development
  # smtp_settings = {
  #   address: ENV.fetch('SMTP_ADDRESS', 'smtp.gmail.com'),
  #   port: ENV.fetch('SMTP_PORT', 587).to_i,
  #   domain: ENV.fetch('SMTP_DOMAIN', 'localhost'),
  #   enable_starttls_auto: ENV.fetch('SMTP_ENABLE_STARTTLS_AUTO', 'true') == 'true'
  # }

  # # Add credentials and authentication only if both are provided
  # smtp_username = ENV['SMTP_USERNAME'].to_s.strip
  # smtp_password = ENV['SMTP_PASSWORD'].to_s.strip
  
  # if smtp_username.present? && smtp_password.present?
  #   smtp_settings[:user_name] = smtp_username
  #   smtp_settings[:password] = smtp_password
  #   smtp_settings[:authentication] = ENV.fetch('SMTP_AUTHENTICATION', 'plain').to_sym
  # else
  #   # If using Gmail and no credentials, raise an error
  #   if ENV.fetch('SMTP_ADDRESS', 'smtp.gmail.com') == 'smtp.gmail.com'
  #     Rails.logger.warn "SMTP_USERNAME and SMTP_PASSWORD must be set to send emails via Gmail"
  #   end
  # end
  
  # Add OpenSSL verify mode if specified
  # if ENV['SMTP_OPENSSL_VERIFY_MODE'].present?
  #   smtp_settings[:openssl_verify_mode] = ENV['SMTP_OPENSSL_VERIFY_MODE']
  # end

  # config.action_mailer.smtp_settings = smtp_settings

  # Print deprecation notices to the Rails logger.
  config.active_support.deprecation = :log

  # Raise exceptions for disallowed deprecations.
  config.active_support.disallowed_deprecation = :raise

  # Tell Active Support which deprecation messages to disallow.
  config.active_support.disallowed_deprecation_warnings = []

  # Raise an error on page load if there are pending migrations.
  config.active_record.migration_error = :page_load

  # Highlight code that triggered database queries in logs.
  config.active_record.verbose_query_logs = true

  # Highlight code that enqueued background job in logs.
  config.active_job.verbose_enqueue_logs = true

  # Raises error for missing translations.
  # config.i18n.raise_on_missing_translations = true

  # Annotate rendered view with file names.
  config.action_view.annotate_rendered_view_with_filenames = true

  # Uncomment if you wish to allow Action Cable access from any origin.
  # config.action_cable.disable_request_forgery_protection = true

  # Raise error when a before_action's only/except options reference missing actions.
  config.action_controller.raise_on_missing_callback_actions = true

  # Apply autocorrection by RuboCop to files generated by `bin/rails generate`.
  # config.generators.apply_rubocop_autocorrect_after_generate!
end
